[platformio]
default_envs = car

[env:car]
platform       = espressif8266
board          = esp12e
framework      = arduino
monitor_speed  = 115200
monitor_port   = COM6
build_src_filter = +<CarUnit/**>
build_flags =
    -DUSE_I2CDEVLIB
lib_deps =
    I2Cdevlib-MPU6050 @ ^1.0.5
    adafruit/Adafruit VL53L1X@^3.1.2
upload_port    = COM6
upload_speed   = 115200

[env:start]
platform       = espressif8266
board          = esp12e
framework      = arduino
monitor_speed  = 115200
monitor_port   = COM4
build_src_filter = +<StartUnit/**>
lib_deps =
    adafruit/Adafruit VL53L1X@^3.1.2

upload_port    = COM4
upload_speed   = 115200

[env:finish]
platform       = espressif8266
board          = esp12e
framework      = arduino
monitor_speed  = 115200
monitor_port   = COM7
build_src_filter = +<FinishUnit/**>
lib_deps =
    adafruit/Adafruit VL53L1X@^3.1.2
upload_speed   = 115200

; Indoor/table profile (toggle as needed)
build_flags =
    -DFINISH_ON_MM=100
    -DFINISH_OFF_MM=140
    -DTIMING_BUDGET_MS=100
  
